apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: polkadot
  namespace: mainnet
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  resources:
    requests:
      storage: 1000Gi
