apiVersion: v1
kind: Service
metadata:
  name: polkadot
  namespace: mainnet
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9615"  
spec:
  type: NodePort
  selector:
    app: polkadot
  ports:
    - name: p2p
      port: 30333
      targetPort: 30333
      nodePort: 30333
      protocol: TCP
    - name: http-rpc
      port: 9933
      targetPort: 9933
      protocol: TCP
    - name: ws-rpc
      port: 9944
      targetPort: 9944
      protocol: TCP
    - name: prometheus
      port: 9615
      targetPort: 9615
      protocol: TCP
